name: 构建并上传docker镜像

on:
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest  # 使用 Ubuntu 系统环境

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # 拉取项目代码

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # 设置 Docker Buildx 支持

      - name: Log in to Docker Hub
        uses: docker/login-action@v2  # 登录到 Docker Hub
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # 从 GitHub Secrets 中获取 Docker Hub 用户名
          password: ${{ secrets.DOCKER_PASSWORD }}  # 从 GitHub Secrets 中获取 Docker Hub 密码

      - name: Build and push Docker image
        uses: docker/build-push-action@v3  # 构建并推送 Docker 镜像
        with:
          context: .  # 当前目录作为构建上下文
          file: ./Dockerfile  # 指定 Dockerfile 文件
          push: true  # 推送镜像到 Docker Hub
          tags: ezio911/free-node:0.3  # 镜像名称和标签